name: check
on:
 pull_request:
  branches:
   - main
jobs:
 test:
  name: Check the source code
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: kuhnroyal/flutter-fvm-config-action@v2
     id: flutter-fvm-config-action
   - uses: subosito/flutter-action@v2
     with:
      flutter-version: ${{ steps.flutter-fvm-config-action.outputs.FLUTTER_VERSION }}
   - name: Install packages
     run: flutter pub get
   - name: Linter
     run: flutter analyze
   - name: Test
     run: flutter test
   - name: Format
     run: dart format .